version: '3.8'

services:
  db:
    image: mysql:8.0  
    container_name: mysql 
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD:=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE:=${MYSQL_DATABASE}
      - MYSQL_USER:=${MYSQL_USER}
      - MYSQL_PASSWORD:=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"  
    volumes:
      - db_data:/var/lib/mysql 
    networks:
      - my_network 

  # redis:
  #   container_name: redis
  #   hostname: redis
  #   command: redis-server --port 6379
  #   labels:
  #     - "name=redis"
  #     - "mode=standalone"
  #   image: "redis:6.2.1-alpine"
  #   ports:
  #     - "6380:6379"


volumes:
  db_data: 

networks:
  my_network: 
