/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as quadraticVotingSol from "./quadraticVoting.sol";
export type { quadraticVotingSol };
import type * as singleVotingSol from "./singleVoting.sol";
export type { singleVotingSol };
export * as factories from "./factories";
export type { QuadraticVotingContract } from "./quadraticVoting.sol/QuadraticVotingContract";
export { QuadraticVotingContract__factory } from "./factories/quadraticVoting.sol/QuadraticVotingContract__factory";
export type { VotingContract } from "./singleVoting.sol/VotingContract";
export { VotingContract__factory } from "./factories/singleVoting.sol/VotingContract__factory";
