/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as quadraticVotingSol from "./quadraticVoting.sol";
export * as singleVotingSol from "./singleVoting.sol";
